name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install and run sushi
        run: |
          npm install -g fsh-sushi
          sushi build

      # Increate Java heap size for publisher
      - name: Set Java heap size
        run: export _JAVA_OPTIONS="$JAVA_TOOL_OPTIONS -Xmx5G"

      # Using this action: https://github.com/qligier/fhir-ig-action
      - name: Generate Implementation Guide (IG)
        # uses: qligier/fhir-ig-action@v0.3.0
        uses: mtnlotus/fhir-ig-action@v0.3.1
        with:
          ig-publisher: "latest"
          sushi: "latest"

      # - name: Install publisher
      #   run: |
      #     wget https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -P ./input-cache
          
      # - name: Update Publisher executable
      #   run: bash _updatePublisher.sh --force --yes

      # TODO: I always get an error with this, cannot find jekyll
      # - name: Generate Implementation Guide (IG)
      #   run: bash _genonce.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
